services:
  test_solver:
    build: .
    image: test_solver:1.0.0
    container_name: test_solver_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/test_solver_db
      API_KEY: ${API_KEY}
      TOKEN_BOT: ${TOKEN_BOT}
      HOST: ${HOST}
      USER: ${USER}
      PASSWORD_DB: ${PASSWORD_DB}
      DBNAME: ${DBNAME}
      PORT: ${PORT}
    restart: unless-stopped

  db:
    image: postgres:17.4-alpine
    container_name: postgres_db

    environment:
      POSTGRES_USER: djan-capcan
      POSTGRES_PASSWORD: cL49I1v0EQgbX0s7Ad
      POSTGRES_DB: test_solver_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U djan-capcan -d test_solver_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  postgres_data:
